### PR TITLE
Make it so library doesn't spit out error, when trying to display 0

### PR DESCRIPTION
**Pull request by Cysioland**

### CODE REVIEW

**Comment by gabrielelana** [comment]
@Cysioland nice! Could you also provide an unit test for this?

**Comment by Cysioland** [comment]
Yes, unit test provided.

**Comment by gabrielelana** [comment]
Cool, but shouldn’t that be `0B`? What do you think?

**Comment by Cysioland** [comment]
Let it be as you wish.

**Comment by gabrielelana** [comment]
Thanks :wink:

**Pull request merged**
